# Generated by Django 2.2.4 on 2019-08-03 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_auto_20190803_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankdetails',
            name='id',
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='ifsc',
            field=models.CharField(default=1, max_length=250, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
