# Generated by Django 2.2.4 on 2019-08-03 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_auto_20190803_1932'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BankDetails',
            new_name='BankData',
        ),
    ]
